services:
  - type: web
    name: africanneurohealth-api
    env: python
    buildCommand: pip install -r requirements_api.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /health
